name: video_conf_test
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.5 <3.0.0" #2.19.5

dependencies:
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.9.34
  socket_io_client: ^2.0.3+1
  cloud_firestore: ^4.8.5
  get_it: ^7.6.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.2
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
