// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFqbLrb8eFlNjlp3A8_lCNTor6BZkM8dI',
    appId: '1:191502626973:web:e1afbaf5ddf1beeed0e474',
    messagingSenderId: '191502626973',
    projectId: 'video-chat-test-c764b',
    authDomain: 'video-chat-test-c764b.firebaseapp.com',
    storageBucket: 'video-chat-test-c764b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl3YScF_IA862lFVS67gO7BamX28gigQQ',
    appId: '1:191502626973:android:0e9c8fa06b98194fd0e474',
    messagingSenderId: '191502626973',
    projectId: 'video-chat-test-c764b',
    storageBucket: 'video-chat-test-c764b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbrek_0nw7AVUD-yJo6vm5H8GKmVSDqvQ',
    appId: '1:191502626973:ios:cbc042d973055c6cd0e474',
    messagingSenderId: '191502626973',
    projectId: 'video-chat-test-c764b',
    storageBucket: 'video-chat-test-c764b.appspot.com',
    iosClientId: '191502626973-t2lj4rvgupopo3uhni4q332qi6agmbb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoConfTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbrek_0nw7AVUD-yJo6vm5H8GKmVSDqvQ',
    appId: '1:191502626973:ios:cbc042d973055c6cd0e474',
    messagingSenderId: '191502626973',
    projectId: 'video-chat-test-c764b',
    storageBucket: 'video-chat-test-c764b.appspot.com',
    iosClientId: '191502626973-t2lj4rvgupopo3uhni4q332qi6agmbb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoConfTest',
  );
}
